services:
  dov:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - .:/app
      - /app/node_modules

  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '5173:5173'
