services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - .:/app
      - /app/node_modules

  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3000:3000'

  nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - prod
